# Generated by Django 6.0 on 2026-01-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aviso_mar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_mar', to='clima.avisomar'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='aviso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='clima.avisometeorologico'),
        ),
    ]
