# Generated by Django 6.0 on 2026-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_comentario_aviso_mar_alter_comentario_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
            ],
        ),
        migrations.RenameField(
            model_name='praia',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='praia',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='avisometeorologico',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='altura_onda',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='direcao_onda',
        ),
        migrations.RemoveField(
            model_name='praia',
            name='temp_agua',
        ),
    ]
