# Generated by Django 6.0 on 2026-01-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacao',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacao',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
