# Generated by Django 6.0 on 2026-01-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_infomar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoMar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('ondulacao', models.CharField(max_length=100)),
                ('vento', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Praia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='InfoMar',
        ),
        migrations.AddField(
            model_name='avisomar',
            name='praia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='clima.praia'),
        ),
    ]
