# Generated by Django 6.0 on 2026-01-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_avisomar_praia_delete_infomar_avisomar_praia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praia',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='praia',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='praia',
            name='altura_onda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='praia',
            name='direcao_onda',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='praia',
            name='temp_agua',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
