# Generated by Django 6.0 on 2026-01-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0004_rename_lat_praia_latitude_rename_lon_praia_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisometeorologico',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avisomar',
            name='praia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviso', to='clima.praia'),
        ),
    ]
